<?php

$userForm = $this->form;
$userForm->prepare();

$formLabel = $this->plugin('formLabel');
$userFieldset = $userForm->get('user_fieldset');
?>

<?php echo $this->form()->openTag($userForm); ?>
    <fieldset>

        <legend>Add User</legend>

        <div class="form-group">
           <?php
           $title = $userFieldset->get('login');
           $title->setAttribute('class','form-control');
                echo $formLabel->openTag() . $this->translate($title->getOption('label')) . $formLabel->closeTag();
                echo $this->formInput($title);
                echo $this->formElementErrors($title);
           ?>
        </div>

        <div class="form-group">
            <?php
            $title = $userFieldset->get('password');
            $title->setAttribute('class','form-control');
            echo $formLabel->openTag() . $this->translate($title->getOption('label')) . $formLabel->closeTag();
            echo $this->formInput($title);
            echo $this->formElementErrors($title);
            ?>
        </div>

        <div class="form-group">
            <?php
            $title = $userFieldset->get('fio');
            $title->setAttribute('class','form-control');
            echo $formLabel->openTag() . $this->translate($title->getOption('label')) . $formLabel->closeTag();
            echo $this->formInput($title);
            echo $this->formElementErrors($title);
            ?>
        </div>


        <div class="PostSelect">
            <?php echo $this->formRow($userFieldset->get('post')); ?>
        </div>



        <div class="form-group">
            <?php
            $title = $userFieldset->get('email');
            $title->setAttribute('class','form-control');
            echo $formLabel->openTag() . $this->translate($title->getOption('label')) . $formLabel->closeTag();
            echo $this->formInput($title);
            echo $this->formElementErrors($title);
            ?>
        </div>




        <div class="RoleSelect">

            <?php echo $this->formRow($userFieldset->get('role')); ?>


         </div>



        <div class="form-element">
            <?php
            $title = $userFieldset->get('avatar');
            $title->setAttribute('class','form-control');
            echo $formLabel->openTag() . $this->translate($title->getOption('label')) . $formLabel->closeTag();
            echo $this->formFile($title);
            echo $this->formElementErrors($title); ?>
        </div>


        <!--<div class="form-group">
            <?php
/*            $title = $userFieldset->get('avatar');
            $title->setAttribute('class','form-control');

            echo $this->formInput($title);
            echo $this->formElementErrors($title);
            */?>
        </div>-->

        <?php
        $submit = $userForm->get('submit');
        $submit->setAttribute('class', 'btn btn-success');
        echo $this->formElement($submit);
        ?>
    </fieldset>
<?php echo $this->form()->closeTag(); ?>

