<table class="table">
    <tr>

        <td>Title</td>
       <td>IsCamera</td>
        <td>IsInternet</td>
      <!--     <td>ID</td>

        -->
    </tr>
    <?php foreach($this->listItems as $pc){ ?>
        <tr>

            <td><?php echo $this->escapeHtml($pc['pc_title']); ?></td>

            <?php
            if(!empty($pc['isCamera'])){
                echo '<td>' . $pc['isCamera'] . '</td>';
            }else{
                echo '<td>'; echo 0; echo '</td>';
            }

            if(!empty($pc['isInternet'])){
                echo '<td>' . $pc['isInternet'] . '</td>';
            }else{
                echo '<td>'; echo 0; echo '</td>';
            }
            ?>
<!--
            <?php
            /*
            <td><?php echo $pc['id']; ?></td>

            if ($pc->getIsCamera()) {
            echo '<td>';
                echo $pc->getIsCamera(); echo '</td>';}
            else {echo '<td>'; echo 0; echo '</td>'; }?>

            <?php if ($pc->getIsInternet()) {
                echo '<td>';
                echo $pc->getIsInternet(); echo '</td>';}
            else {echo '<td>'; echo 0; echo '</td>'; }
            */
            ?>
            -->
        </tr>
    <?php } ?>
</table>