<table class="table">
    <?php foreach($this->listItems as $room){ ?>
        <tr>
            <td><?php echo $room->getId(); ?></td>
            <td><?php echo $this->escapeHtml($room->getTitle()); ?></td>
            <?php
                if($room->getPc()){
                    echo '<td>' . $room->getPc()->getTitle() . '</td>';
                }
            ?>
        </tr>
    <?php } ?>
</table>