<table class="table">
    <?php foreach($this->listItems as $meetingroom){ ?>
        <tr>
            <td><?php echo $meetingroom->getId(); ?></td>
            <td><?php echo $this->escapeHtml($meetingroom->getTitle()); ?></td>
            <?php
            if($meetingroom->getPc()){
                echo '<td>' . $meetingroom->getPc()->getTitle() . '</td>';
            }
            ?>
        </tr>
    <?php } ?>
</table>