<table class="table">
    <tr>
        <td>ID</td>
        <td>Title</td>
        <td>Camera</td>
        <td>Internet</td>
    </tr>
    <?php foreach($this->listItems as $pc){ ?>
        <tr>
            <td><?php echo $pc->getId(); ?></td>
            <td><?php echo $this->escapeHtml($pc->getTitle()); ?></td>
            <td><?php echo $pc->getIsCamera(); ?></td>
            <td><?php echo $pc->getIsInternet(); ?></td>
        </tr>
    <?php } ?>
</table>