<div class="jumbotron">
    <h1><?php echo $this->mylowercase($this->title); ?></h1>
    <a href='<?=$this->url('rooms', array('action'=> 'edit', 'id' => 2)); ?>'>Edit room</a></div>
<?php
echo $this->partial(
        'meeting-room/elements/table',
         array('listItems' => $this->listMeetingRoom)
     );
?>
<a href='<?=$this->url('pcs', array('action'=> 'edit', 'id' => 1)); ?>'>EDIT</a></div>
<?php
echo $this->partial(
    'meeting-room/elements/table',
    array('listItems' => $this->listPC)
);
?>
