
<div>
    <h3><?php echo $this->title?></h3>
</div>
<?php
$form=$this->form;
//$url=$this->url('pcpc',array('controller'=>'pc','action'=>'add'));
//$form->setAttribute('action', $url)->prepare();
$form->prepare();
?>
<?php
echo $this->form()->openTag($form);

$pc = $form->get('pc');

echo $this->formRow($pc->get('title'));
echo '<br/>';
/*var_dump($pc->get('is_internet'));*/
echo $this->formRow($pc->get('is_internet'));
echo '<br/>';
echo $this->formRow($pc->get('is_camera'));
echo '<br/>';
//echo $this->formCollection($pc->get('is_camera'));

//$brand = $product->get('brand');

/*echo $this->formRow($brand->get('name'));
echo $this->formRow($brand->get('url'));

echo $this->formHidden($form->get('csrf'));*/
echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();


?>
