<?php
/*$form->setAttribute('action', $this->url('home'))
    ->prepare();*/

echo $this->form()->openTag($form);

$pc = $form->get('pc');

echo $this->formRow($pc->get('title'));
echo $this->formRow($pc->get('is_internet'));
echo $this->formCollection($pc->get('is_camera'));

//$brand = $product->get('brand');

/*echo $this->formRow($brand->get('name'));
echo $this->formRow($brand->get('url'));

echo $this->formHidden($form->get('csrf'));*/
echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();

?>


<?php
/*$form=$this->form;
$formLabel=$this->plugin('formLabel');

echo $this->form()->openTag($form);
*/?><!--

<fieldset>
    <legend>
        <?php /*echo $this->title;*/?>
        <?php
/*        $title=$form->get('title');
        echo $formLabel->openTag().$title->getOption('label').$formLabel->closeTag();
        echo $this->formInput($title);
        echo $this->formElementErrors($title);

        echo '<br/>';

        $isCamera=$form->get('is_camera');
        echo $formLabel->openTag().$isCamera->getOption('label').$formLabel->closeTag();
        echo $this->formInput($isCamera);
        echo $this->formElementErrors($isCamera);

        echo '<br/>';

        $isInternet=$form->get('is_internet');
        echo $formLabel->openTag().$isInternet->getOption('label').$formLabel->closeTag();
        echo $this->formInput($isInternet);
        echo $this->formElementErrors($isInternet);

        echo '<br/>';

        $submit=$form->get('submit');
        echo '<br/>'.$this->formInput($submit);



        */?>
    </legend>
</fieldset>
--><?php /*echo $this->form()->closeTag($form);*/?>