<?php
/** @var \Zend\Form\Form $form */
$form = $this->form;
$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);

?>

<?php echo $this->form()->openTag($form); ?>
<fildset>
    <legend><?php echo $this->title ?> </legend>
    <?php
        $title = $form->get('title');
        echo $formLabel->openTag() . $title->getOption('label'). $formLabel->closeTag();
        echo $this->formInput($title);
        echo $this->formElementErrors($title);

    echo '<br/>';

    $isCamera = $form->get('is camera');
    echo $formLabel->openTag() . $isCamera->getOption('label'). $formLabel->closeTag();
    echo $this->formInput($isCamera);
    echo $this->formElementErrors($isCamera);

    echo '<br/>';

    $isInternet = $form->get('is internet');
    echo $formLabel->openTag() . $isInternet->getOption('label'). $formLabel->closeTag();
    echo $this->formInput($isInternet);
    echo $this->formElementErrors($isInternet);

        $submit = $form->get('submit');
    echo '<br/>' . $this->formInput($submit);
    ?>
</fildset>
<?php echo $this->form()->closeTag($form); ?>