<?php
/**
 * @var \Zend\Form\Form $form
 */
$form = $this->form;

$form->prepare();

echo $this->form()->openTag($form);

echo $this->title;

echo '<br/>';

$pc = $form->get('pc');

echo $this->formRow($pc->get('title'));

echo '<br/>';

echo $this->formRow($pc->get('is_camera'));

echo '<br/>';

echo $this->formRow($pc->get('is_internet'));

echo '<br/>';

echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag($form);
