<?php
/** @var \Zend\Form\Form $form */
$form = $this->form;
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);

?>

    <fieldset>
        <legend>
            <?php
            echo $this->title;
            ?>
        </legend>
        <?php
        $title = $form->get('title');
        echo $formLabel->openTag() . $title->getOption('label');
        echo $this->formInput($title);
        echo $this->formElementErrors($title);
        echo $formLabel->closeTag();

        echo '<br/>';

        $isCamera = $form->get('is_camera');
        echo $formLabel->openTag() . $isCamera->getOption('label');
        echo $this->formInput($isCamera);
        echo $this->formElementErrors($isCamera);
        echo $formLabel->closeTag();

        echo '<br/>';

        $isInternet = $form->get('is_internet');
        echo $formLabel->openTag() . $isInternet->getOption('label');
        echo $this->formInput($isInternet);
        echo $this->formElementErrors($isInternet);
        echo $formLabel->closeTag();

        echo '<br/>';

        $submit = $form->get('submit');
        echo $this->formInput($submit);

        ?>

    </fieldset>

<?php
echo $this->form()->closeTag($form);
?>