<?php
/** @var \MeetingRoom\Entity\MeetingRoom $meetingRoom */
/*$meetingRoom = $this->result;
?>
<div>
    <h1><?php echo $this->title; ?></h1>
    <?php
        if($meetingRoom){
            echo 'Title: ' . $meetingRoom->getTitle();
            echo '<br/>';
            echo 'Place: ' . $meetingRoom->getPlace();
            echo '<br/>';

            if($meetingRoom->getPc()){
                echo 'Title PC:' . $meetingRoom->getPc()->getTitle();
                echo '<br/>';
                echo 'Is camera:' . $meetingRoom->getPc()->getIsCamera();
            }
        }
    ?>
</div>
<div>
    <?php
    if($this->error){
        echo $this->error;
    }
    ?>
</div>*/

$form=$this->form;

echo $this->form()->openTag($form);
$pc=$form->get('pc');
echo $this->formRow($pc->get('title'));
echo "<br/>";
echo $this->formRow($pc->get('is_internet'));
echo "<br/>";
echo $this->formRow($pc->get('is_camera'));
echo "<br/>";
echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();
?>