<?php
/** @var Zend\Form\Form $form */
$form=$this->form;
?>
    <div>
        <h1><?php echo $this->title; ?></h1>
    </div>
<?php echo $this->form()->openTag($form)?>
    <fieldset>
        <legend><?php echo $this->title;?></legend>
        <?php
        $title = $form->get('title');//$title - елемент формы (new Element)
        echo $formLabel->openTag() . $title->getOption('label') . $formLabel->closeTag();
        echo $this->formInput($title);
        echo $this->formElementErrors($title);
        //echo $formLabel->formElemen($title);
        $submit = $form->get('submit');
        echo '<br/>' . $this->formInput($submit);
        ?>
    </fieldset>
<?php echo $this->form()->closeTag($form)?>