<?php
$form->setAttribute('action', $this->url('pc', array('action'=>'edit')))
   ->prepare();

echo $this->form()->openTag($form);

$pc = $form->get('pc');

echo $this->formRow($pc->get('title'));
echo $this->formRow($pc->get('is_camera'));
echo $this->formRow($pc->get('is_internet'));



echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();
?>