<div class="jumbotron">
    <h1><?php echo $this->mylowercase($this->title); ?></h1>
    <a href='<?=$this->url('pc', array('action'=> 'edit', 'id' => 2)); ?>'>Edit pc</a></div>
<?php
echo $this->partial(
    'meeting-room/elements/table',
    array('listItems' => $this->listPc)
);
?>


<?php

$form = $this->form;
$formlabel = $this->plugin('formlabel');
?>


<?php echo $this->form()->openTag($form) ?>
<firldset>
    <legend><?php echo $this->title?></legend>
    <?php
    $title = $form->get('title');
    echo $formlabel->openTag().$title->getOption('Label');
    echo $this->formInput($title);
    echo $this->formElementErrors($title);
    //echo $formlabel->closetag();

    echo '<br>';

    $isInternet = $form->get('is_camera');

    ?>
</firldset>


<?php echo $this->form()->closeTag($form) ?>