<?php
/* @var \Zend\Form\Form $form */
$form = $this->form;


echo $this->form()->openTag($form);
?>
<fieldset>
    <legend><?php echo $this->title; ?></legend>
    <?php
    $title = $form->get('title');
    echo $formLabel->openTag() . $title->getOption('label');
    echo $this->formInput($title);
    echo $this->formElementErrors($title);
    echo $formLabel->closeTag();
    ?>
</fieldset>
<?php echo $this->form()->closeTag($form); ?>
