<div class="jumbotron">
    <h1><?php echo $this->mylowercase($this->title); ?></h1>
    <a href='<?=$this->url('pc', array('action'=> 'edit', 'id' => 2)); ?>'>Edit pc</a></div>
<table border="1">
    <?php
    /*echo $this->partial(
        'meeting-room/elements/table',
        array('listItems' => $this->listPc)
    );*/
    //var_dump($this->listPC);
    foreach($this->listPc as $pc)
    {
        echo '<tr><td>'.$pc->getId().'<td>'.$pc->getTitle().'<td>'.$pc->getIsCamera().'<td>'.$pc->getIsInternet().'</td><td><a href="'.$this->url('pc',array('action'=>'edit', 'id'=>$pc->getId())).'">Edit</a></td></tr>';
    }
    ?>

</table>