<a href="<?php echo $this->url('rooms', array('action' => 'add'));?>">
    <div class="btn btn-large btn-primary" type="button">
        <?php echo $this->translate('Добавление переговорной комнаты');?>
    </div>
</a>

<table class="table">
    <thead>
        <th><?php echo $this->translate('Название'); ?></th>
        <th><?php echo $this->translate('Место проведения'); ?></th>
        <th><?php echo $this->translate('Вместимость'); ?></th>
        <th><?php echo $this->translate('Действие'); ?></th>
    </thead>
    <?php foreach($this->listMR as $meetingRoom){ ?>
        <tr>
            <td><?php echo $meetingRoom->getTitle(); ?></td>
            <td><?php echo $meetingRoom->getPlace(); ?></td>
            <td><?php echo $meetingRoom->getCapacity(); ?></td>
            <td align="left">
                <a href="<?php echo $this->url('rooms', array('action' => 'edit', 'id' => $meetingRoom->getId())); ?>">
                    <div class="btn btn-mini btn-warning" type="button">
                        <?php echo $this->translate('Редактировать');?>
                    </div>
                </a>
            </td>
        <tr>
    <?php } ?>
</table>