<table class="table">
    <thead>
        <th><?php echo $this->translate('Title'); ?></th>
        <th><?php echo $this->translate('Is camera'); ?></th>
        <th><?php echo $this->translate('Is internet'); ?></th>
        <th><?php echo $this->translate('Action'); ?></th>
    </thead>
    <?php foreach($this->listPc as $pc){ ?>
        <tr>
            <td><?php echo $pc->getTitle(); ?></td>
            <td><?php echo $pc->getIsCamera(); ?></td>
            <td><?php echo $pc->getIsInternet(); ?></td>
            <td>
                <a href="<?php echo $this->url('pc', array('action' => 'edit', 'id' => $pc->getId())); ?>"><?php echo $this->translate('Edit'); ?></a>
            </td>
        <tr>
    <?php } ?>
</table>